### ISSUE TITLE
Likes/Read Reviews Button

### ISSUE THREAD

**Issue by jdphiladelphia** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#110]
Dear S3Bubble,

We love S3Bubble! I am reporting a weird UI issue for the LIKE button.

When website visitors click the LIKE button, it requires them to explain why they liked it and forces them to type 100 characters. From our beta testing, users dislike this BIG time. So much so that we disabled the LIKE button. They just want the like button to indicate they liked it (like the heart on Etsy or Pinterest), or the Like on Facebook.

Is it possible to let people "LIKE" a movie without explaining why, or at least allowing them to do a minimum of 5 characters instead of 100? And is there any way to edit the window that pops up?

Here is how it looks:  https://www.screencast.com/t/pnX52MQcWn

![image](https://user-images.githubusercontent.com/24858286/43812241-46090552-9a8e-11e8-96ac-602931006497.png)

Respectfully,
JD

**Comment by s3bubble** [comment]
We have changed the likes and reviews with the latest version https://streamiumtheme.com
