### ISSUE TITLE
More Subtle Error Messages

### ISSUE THREAD

**Issue by jdphiladelphia** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#112]
Greetings S3Bubble,

We had an unfortunate occasion where someone clicked into a menu category from the top menu, then clicked View All, then saw this error message at the top of the page:

![image](https://user-images.githubusercontent.com/24858286/43822798-2aceab16-9abb-11e8-8afe-af64b7a9db79.png)

"S3Bubble Media Streaming: To display an image here go to your custom post and look for the metabox (Mail Slider Video) and check it)."

Wowsers.  So we learned the hard way that every Genre must have a Slider ticked to show in the Slider area, even if we did not want to highlight a genre as such. In addition we learned it cannot be a simple still like the default home (movie directory) page, a video clip is required.

My request is that a default image, perhaps the site's custom logo appears here instead -- or provide us a way to reword a message such as this one (my client was not too happy).

Regards,
JD

**Comment by s3bubble** [comment]
Hi @jdphiladelphia 

Thanks for highlighting this you can probably hide the header section completely with some css until we apply a fix for this.

something like this.
~~~
.archive .slick-list {
    display: none;
}
~~~
