### ISSUE TITLE
disconnecting website from S3Bubble

### ISSUE THREAD

**Issue by newibn** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#113]
## Description
Briefly describe the issue.
Include an example link to your issue on the Streamium theme
I was locked out of my previous WP account using Indiebcast.com through S3Bubble. So I decided to cancel my account and create everything from scratch. When I'm in my new account "Newibn" on S3Bubble and I try to connect my website "indiebcast.com" it gives me an error that it is connected to the old account even though I deleted the website and got a confirmation that it was deleted. How do I add my website to my new account? 
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. logged into S3Bubble account.
2. Went to connected website, deleted website and got confirmation that website was deleted.
3.Logged into new S3bubble account and tried to connect my website and i get an error that it is already connected to the old account.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:

#### Streamium Theme
what version of the theme are you using? the latest verison
#### browsers chrome
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected? MacOs

**Comment by s3bubble** [comment]
This has been fixed

**Comment by newibn** [comment]
Yes
