### ISSUE TITLE
Request for GeoLocation of Content

### ISSUE THREAD

**Issue by DrStupit** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#117]
Hey Sam & Team
I would just like to find out, is it possible to hide a specific category of posts, from a specific country ? 

Kind Regards 
Kerev

**Comment by s3bubble** [comment]
This can now easily be done by adding Geo Restriction to your CloudFront Distributions.

https://s3bubble.com/app/#/cloudfront

![screenshot 2019-01-23 at 14 46 04](https://user-images.githubusercontent.com/17534854/51614479-a4beef80-1f1d-11e9-9738-f9645774587c.png)

Blacklist or Whitelist countries
