### ISSUE TITLE
"View all movies" url 404

### ISSUE THREAD

**Issue by christianmilano** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#119]
Hi, I have a problem with my "view all [nameofcategory]" link above the categories slides.
I rename "movies" to "videos", but in my menu I have "Videos" and my categories have http://www.mydomain.com/?movies=crime-films
anyway, it works and I can list all "crime-films" category videos.
But in "view all [nameofcategory]" above slides my url is "http://www.mydomain.com/videos/crime-films" and it doesn't work.
Tried resetting permalinks but nothing happens.

**Comment by s3bubble** [comment]
Hi @christianmilano,

Please email us your live links to support@s3bubble.com its to hard to debug without them.

We can't seem the ever get a link with ?movies=something on the streamium theme https://streamiumtheme.com
