### ISSUE TITLE
Videos not streaming

### ISSUE THREAD

**Issue by newibn** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#120]
## Description
Briefly describe the issue.
Include an example link to your issue on the Streamium theme

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Upload the video
2. Encode video to 720 S3Bubble preset
3. view/edit media try to play video and get an error message
<img width="672" alt="screen shot 2018-10-19 at 7 52 23 am" src="https://user-images.githubusercontent.com/42871534/47219853-9fc62f00-d375-11e8-8e4d-31f6d368ce15.png">

I am using the most up to date streamium theme. I just installed it a month ago.
I am unsure why videos wont play now. It was playing fine a week ago. 

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:

#### Streamium Theme
what version of the theme are you using?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?

**Comment by s3bubble** [comment]
Do you have hls cors enabled on your bucket?

Are you using Cloudfront?

**Comment by newibn** [comment]
Yes I am using Cloudfront. How would I check the those settings on my bucket?
