### ISSUE TITLE
woocomerce upgrade

### ISSUE THREAD

**Issue by moh1122** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#123]
Hello
After upgrading woocomerce today an alert message pop up saying:
Your theme (S3Bubble Streamium Pro Theme) contains outdated copies of some WooCommerce template files. These files may need updating to ensure they are compatible with the current version of WooCommerce. Suggestions to fix this:

Update your theme to the latest version. If no update is available contact your theme author asking about compatibility with the current WooCommerce version.
If you copied over a template file to change something, then you will need to copy the new version of the template and apply your changes again.

Here are my logs:

### WordPress Environment ###

Home URL: http://54.200.80.250
Site URL: http://54.200.80.250
WC Version: 3.5.5
Log Directory Writable: ✔
WP Version: 5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.13
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 8.0.13
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 441.36MB
Database Data Size: 440.45MB
Database Index Size: 0.91MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 439.47MB + Index: 0.05MB
wp_postmeta: Data: 0.14MB + Index: 0.03MB
wp_posts: Data: 0.22MB + Index: 0.06MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wsal_metadata: Data: 0.02MB + Index: 0.02MB
wp_wsal_occurrences: Data: 0.02MB + Index: 0.02MB
wp_wsal_options: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 26
customize_changeset: 30
movie: 9
nav_menu_item: 16
page: 7
post: 2
product: 1
revision: 60
sport: 4

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (9) ###

LoggedIn - Limit Active Logins: by Joel James – 1.0.1
Mailchimp for WooCommerce: by Mailchimp – 2.1.13 – Not tested with the active version of WooCommerce
Post Types Order: by Nsp Code – 1.9.3.9
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.5.5
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.9
WooCommerce Stripe Gateway: by WooCommerce – 4.1.14
WooCommerce Services: by Automattic – 1.19.0
WooCommerce: by Automattic – 3.5.5
WP Extended Search: by 5um17 – 1.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: grouped (grouped)
variable (variable)
external (external)
simple (simple)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
exclude-from-search (exclude-from-search)
rated-5 (rated-5)

### WC Pages ###

Shop base: #55 - /plans/
Cart: #56 - /cart/
Checkout: #57 - /checkout/
My account: #58 - /my-account/
Terms and conditions: #3 - /privacy-policy/

### Theme ###

Name: S3Bubble Streamium Pro Theme
Version: 2.2
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: WordPress-Netflix-Style-Video-Streaming-Theme/woocommerce/archive-product.php
WordPress-Netflix-Style-Video-Streaming-Theme/woocommerce/checkout/form-checkout.php
WordPress-Netflix-Style-Video-Streaming-Theme/woocommerce/content-product.php
WordPress-Netflix-Style-Video-Streaming-Theme/woocommerce/global/breadcrumb.php
WordPress-Netflix-Style-Video-Streaming-Theme/woocommerce/global/sidebar.php
WordPress-Netflix-Style-Video-Streaming-Theme/woocommerce/global/wrapper-end.php
WordPress-Netflix-Style-Video-Streaming-Theme/woocommerce/global/wrapper-start.php
WordPress-Netflix-Style-Video-Streaming-Theme/woocommerce/myaccount/form-login.php
WordPress-Netflix-Style-Video-Streaming-Theme/woocommerce/myaccount/form-lost-password.php
WordPress-Netflix-Style-Video-Streaming-Theme/woocommerce/myaccount/form-reset-password.php version 3.5.0 is out of date. The core version is 3.5.5
WordPress-Netflix-Style-Video-Streaming-Theme/woocommerce/myaccount/lost-password-confirmation.php
WordPress-Netflix-Style-Video-Streaming-Theme/woocommerce/myaccount/navigation.php
WordPress-Netflix-Style-Video-Streaming-Theme/woocommerce/single-product.php

Outdated Templates: ❌

**Comment by s3bubble** [comment]
Hi @moh1122

Thanks for the info Woocommerce probably updated some files for Wordpress 5.1 release we will update these for the next release it won’t affect any functionality.

Best Regards 

Support

**Comment by moh1122** [comment]
thnk you @s3bubble  for your quick reply
