### ISSUE TITLE
Recommended to watch

### ISSUE THREAD

**Issue by moh1122** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#126]
Hello
We are in our beta testing phase and we will go live hopefully in a couple of months.
I would like to ask if I need to add a recommended to watch category per user.
How can we do that?
Thank you on advance.

**Comment by s3bubble** [comment]
Hi @moh1122

If you are looking for lots of custom modification it may be worth looking at our enterprise package on the pricing page or our partnership program here.

https://s3bubble.com/partner

**Comment by moh1122** [comment]
Hello @s3bubble thank you for your quick reply well we dont have lots of modifications we only have a bit and we already asked them here. As a start we are thinking to start with the premium package and we started our upload process and after that if we have lots of media views we will upgrade our plan. We are looking forward for further updates?
