### ISSUE TITLE
Authentication broken for API access

### ISSUE THREAD

**Issue by cnibeck** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#129]
## Description
Briefly describe the issue.
Include an example link to your issue on the Streamium theme
Any authenticated requests to the API such as https://imediatv.net/api/wc/v2/orders fail with a 401 access denied. Switch themes to default WP and it works. Note the URI changes. https://imediatv.net/wp-json/wc/v2/orders
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Authenticated API call to https://imediatv.net/api/wc/v2/orders
2.Fails with "Sorry, you cannot list resources." 401 error
3. Switch themes and then works

### Expected
Please describe what you expected to see.
JSON Response
### Actual
Please describe what actually happened.
Error 401
### Error output
If there are any errors at all, please include them here.
{
  "code": "woocommerce_rest_cannot_view",
  "message": "Sorry, you cannot list resources.",
  "data": {
    "status": 401
  }
}
## Additional Information
Please include any additional information necessary here. Including the following:

#### Streamium Theme
what version of the theme are you using?
2.2
#### browsers
what browser are affected?
all including curl insomnia and postman
#### OSes
what platforms (operating systems and devices) are affected?
All

**Comment by cnibeck** [comment]
Greetings!  Thanks for your awesome work….

I am attempting to get the Woocommerce API working but having problems getting the authentication working.

If I switch to another Theme other than the Streaming theme the API path switches to wp-json and basic authentication authenticates.

Under streamium the API endpoint is API/… and anything that does not require authentication works….  https://iMediaTV.net/api/wc/v2/

Switch out of streamium like https://iMediaTV.net/wp-json/wc/v2/orders. And authentication works.

**Comment by s3bubble** [comment]
Hi @cnibeck 

Thanks for all the info we will look into this.

**Comment by s3bubble** [comment]
Hi @cnibeck 

If you pull the latest version into your project.

We have added a list of api calls here: https://github.com/s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme

To list Woocommerce orders you can use the following url.

https://streamiumtheme.com/wp-json/wc/v2/orders?consumer_key=ck_999&consumer_secret=cs_999

Obviously change the keys to your keys.
