### ISSUE TITLE
join now button

### ISSUE THREAD

**Issue by archeggs23** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#130]
on the join now page the button that was generated how do we change what the button says, we dont want to offer the subscription free for a month and we dont want to false advertise to the people subscribing. how do we change what the button says 

![Screen Shot 2020-02-03 at 1 40 27 PM](https://user-images.githubusercontent.com/60622779/73680787-e8991880-468a-11ea-93a5-f7222857146e.png)

**Comment by archeggs23** [comment]
is there anyone on here? is there anyone to help me  with this issue?

**Comment by s3bubble** [comment]
Hi @archeggs23 

You can do this by changing the language file. 

https://www.ostraining.com/blog/wordpress/language-strings-wordpress/

**Comment by s3bubble** [comment]
Hi @archeggs23 

We have done a video tutorial explaining the process in full.

https://www.youtube.com/watch?v=9P7XsSpQVFQ

Best Regards

**Comment by archeggs23** [comment]
okay thanks ill check it out right now , and one last thing and ill be good
to go , i also designed my logo in canva, but when i upload my logo in the
stremium styles my logo is very very small, i changed the dimensions of the
logo to 1586 x 527 but when i change the dimension and upload the logo its
still super small on the platform, im not sure what to do to make the logo
bigger on the platform

**Comment by archeggs23** [comment]
[image: Screen Shot 2020-02-11 at 10.00.00 AM.png]

**Comment by archeggs23** [comment]
thanks for the response & solution, well appreciated

**Comment by archeggs23** [comment]
& when i type in " join for a month free" in the filter translator the join
for a month free option doesnt pop up , only options that pop up are (
enable join page redirect) ( join page options ) and ( join template ) does
this mean i need to update the theme? or am i doing something wrong

**Comment by archeggs23** [comment]
fixed the button everythings good thanks for your help, i really appreciate
the guidance , but my logo is still really really small i changed the
dimensions but its still really small , not sure what to do

**Comment by s3bubble** [comment]
Please create another issue for the logo is possible can you send your logo to support@s3bubble.com so we can test with it

**Comment by archeggs23** [comment]
fixed it thanks , appreciate your support team
