### ISSUE TITLE
RTL support 

### ISSUE THREAD

**Issue by devahmadmohammadi** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#50]
Is there any support for RTL websites ? if not would you please provide a RTL.css file for our website?

**Comment by s3bubble** [comment]
Hi @devahmadmohammadi 

We have a rtl player theme added in the brand section here.

https://s3bubble.com/secure/#/dashboard_brand

We need to make the theme rtl still I will leave this open
