### ISSUE TITLE
Footer Problem

### ISSUE THREAD

**Issue by KyleJ144** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#52]
I am currently using the streamium them that i downloaded from your website and i am wondering what footer plugins are compatible with the theme and how do i add a custom footer.

**Comment by jdphiladelphia** [comment]
I have the same question. Thank you in advance!

**Comment by fullnapsis** [comment]
how can I edit  footer of stremium theme anyone????

**Comment by s3bubble** [comment]
Hi All,

The only thing you can currently change in the footer is the powered by text this can be done under.

Apperance -> Customizer -> Site Identity

Please see this image.
![screen shot 2018-02-08 at 09 47 28](https://user-images.githubusercontent.com/17534854/35966289-4dcaca4e-0cb5-11e8-8ab3-e16844d2e978.png)

We can take a better look at the footer for the next release.

What sort of functionality are you all looking for?

Best Regards

S3Bubble

**Comment by jdphiladelphia** [comment]
Hi there s3bubble,

First, thanks for a fantastic theme.

A basic footer like the one at the bottom of www.netflix.com would work for many of your customers.

Many themes allow simple footers like that to be created using widgets.

Here is the footer I put on our movie site, scroll to the very bottom:  http://flixpics.com/welcome

Thanks for your consideration!

Regards,
JD
