### ISSUE TITLE
Multiple BG Videos on Homepage Slider

### ISSUE THREAD

**Issue by DrStupit** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#62]
Hi All 
I'm having an issue, where I select multiple posts to have a video on the BG Slider. 
Yet only one video plays on the homepage slider. 

Any work around this? Or is it only allowed to play one video?

**Comment by s3bubble** [comment]
Hi @DrStupit 

We are going to change the way the main slider works with the next update we will be moving it into its own menu like ratings and have multiple options the theme has grow out of the older slider setup and it  doesn't make sense to have to search and find each post you have a slider button checked for.

Best Regards

Support

**Comment by jdphiladelphia** [comment]
Dear s3Bubble,

Looking forward to the new main slider!

Question: Please consider adding the ability to change how fast/slow the slides rotate. For example, my client wants the background video of the trailer to play longer than it currently plays before changing to the next slide.

Respectfully,
JD
