### ISSUE TITLE
Autoplay Tv Programs

### ISSUE THREAD

**Issue by techcrunchnz** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#69]
Hi There,

I would really appreciate if someone could help me figure out how to make the player automatically play the next video when viewing Tv Programs.

My website is currently fetching youtube videos from selected playlists & gets populated under Tv Programs. I have categorized each Tv show & would like to know its possible to make the player play the next video in a category when one episode is watched.

Right now, it just stops after viewing One video.

Cheers!

**Comment by mstorne** [comment]
If you found out the way to do it, please let me know.
Thank you,
Marko.
