### ISSUE TITLE
Autoplay Next Video

### ISSUE THREAD

**Issue by techcrunchnz** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#73]
Hi There,

Is there an option to autoplay videos after one ends?

Cheers

**Comment by mstorne** [comment]
I am looking for the same feature. There is a field Multiple Videos / Series, I tried to set it up, but once the first video is ended, it redirects me to home page instead to next one. 
Thank you.

**Comment by realwildgirls** [comment]
Would like to have this feature as well . Any progress?

**Comment by techcrunchnz** [comment]
I wrote a plugin to make a playlist in s3bubble tv shows so it immediately plays the next video. will upload to the wp plugin repository & post the url here.

**Comment by realwildgirls** [comment]
Awesome!! I need this ASAP. Will pay for premium.

Thanks
