### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by mitcholi** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#76]
Parse error: syntax error, unexpected '[', expecting ')' in /home/content/28/10641728/html/urbantravelnet/wp-content/themes/Streamium-Netflix-Theme-master/inc/theme/ratings.php on line 18

**Comment by s3bubble** [comment]
Hi @mitcholi

Thanks for highlighting this these issues are normally related to older version of php we will look into it.
