### ISSUE TITLE
Changing S3 Bucket Region

### ISSUE THREAD

**Issue by DrStupit** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#77]
Hi Guys

I would like to know, can I change my S3 bucket region, without it having a negative effect on my website using the Streamium Theme? 

I would like to switch from usa-east-1 to Dublin-Ireland. 

As Ireland is closer to South Africa? 

Is this possible? and what are any of the negative effects that I may encounter doing this swap. 

Regards 
Kerev

**Comment by s3bubble** [comment]
You can now use any region
