### ISSUE TITLE
[Bug Report] Taxonomy not Displaying Properly

### ISSUE THREAD

**Issue by jdphiladelphia** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#82]
Dear S3Bubble,

Help please. A weird issue just started. One the main directory page, the main Custom PostType name (in this case "Movie") is missing. See screenshot below.

However, I see the name just fine when I go directly to the Movies Page which lists only rows in that Custom PostType.

The issue persists even with all Plugins disabled.

Any idea what the issue might be?

![image](https://user-images.githubusercontent.com/24858286/38166367-c157a79e-34f0-11e8-872e-25f86692284b.png)

Regards,
JD

**Comment by s3bubble** [comment]
Hi @jdphiladelphia 

Can you send us a link please

**Comment by jdphiladelphia** [comment]
Yes, here is the link: http://flixpics.com/browse

**Comment by s3bubble** [comment]
fixed
