### ISSUE TITLE
[Question] Google Analytics (media.s3bubble.com)

### ISSUE THREAD

**Issue by jdphiladelphia** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#83]
Dear S3 Bubble,

It was very easy to setup GA tracking on each movie. That data is critical for us. Thank you!!

Question: Are customers expected to maintain two GA accounts?  One using the http://media.s3bubble.com URL to track video play stats--and then another GA account to track traffic to the website's live URL?  For example, the website I manage has pages other than ones that play movies, such as Landing Pages and a Blog/news section. So I must track that data too.

If I'm able to merge the Video play stats and web traffic stats into one united GA report, that would be a dream come true. I will research more to see if there is a way to do it. 

Meanwhile, does S3Bubble or anyone else have suggestions?

P.S. For reference, if there is anyone reading this who needs to setup GA stats per video, use this helpful video:  https://youtu.be/fozIRvpoU9o

Respectfully,
JD

**Comment by Samaxx** [comment]
Why not just use 1 GA tracking code for both videos and the website and sort in GA by Behavior > Site Content?

**Comment by jdphiladelphia** [comment]
@Samaxx , I'm not sure you are clear of the dilemma.

The only way to track AWS-hosted videos inside S3Bubble's Dashboard is to use THEIR URL. The videos are hosted by THEM, not me or the site I manage. So that GA report will not show web traffic, only movie plays. I need to show both movie plays and web traffic.

media.s3bubble.com is not my site, but that is the required URL to track movie plays.

Regards,
JD

**Comment by s3bubble** [comment]
We are no longer using media.s3bubble.com
