### ISSUE TITLE
Tile Expansion Bug

### ISSUE THREAD

**Issue by DrStupit** [s3bubble/WordPress-Netflix-Style-Video-Streaming-Theme#95]
Hi Guys 
I have detected an error on the Streamium theme. 
I'm unsure if this has been brought up before, but when you expand a tile, and then close it. The tile becomes inactive until another till is open and closed and then only can the previous tile be expanded again? 
Is it a Javascript issue ? That can have a simple implementation to fix? 

Kind Regards 
Kerev

**Comment by s3bubble** [comment]
Hi @DrStupit 

Yes, it was mentioned before but I don't think we understood the issue after checking again I see what you mean.

We will apply a fix for this we are just working on Roku integration at the moment getting everything setup for their direct publisher service then we will be moving back to clear some of these issues for the next release.

Thanks

Sam

**Comment by s3bubble** [comment]
This should be fixed
